# Generated by Django 4.2.7 on 2024-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='end_date',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='main_plan',
            field=models.BooleanField(blank=True, null=True, verbose_name=False),
        ),
    ]
