# Generated by Django 4.2.7 on 2024-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trainingplan_end_date_trainingplan_main_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='main_plan',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
