# Generated by Django 4.2.7 on 2024-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trainingplan_main_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
