# Generated by Django 5.0 on 2024-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trainingplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raports',
            name='date',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
